### ISSUE TITLE
빨리 누르면 뽑기했던 캐릭터가 없어져요

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#101]
8000정도 썼는데 못받았네요

**Comment by devxb** [comment]
@sumi-0011 
@hyesungoh 

이거 서버측 로그는 정상지급된거로 보이는데, 펫 뽑기 하고 새로고침하지 않으면 획득한 펫이 보이지 않아서 발생하는 이슈 같습니다.

+ 문의남기신분 남지 않아서 대응이 쉽지 않은데, Assignees에 문의 남기신분 추가하는게 힘든 상황인걸까요??

**Comment by sumi-0011** [comment]
> @sumi-0011 @hyesungoh
> 
> 이거 서버측 로그는 정상지급된거로 보이는데, 펫 뽑기 하고 새로고침하지 않으면 획득한 펫이 보이지 않아서 발생하는 이슈 같습니다.
> 
> * 문의남기신분 남지 않아서 대응이 쉽지 않은데, Assignees에 문의 남기신분 추가하는게 힘든 상황인걸까요??

최근에 수정한 사항인데, 어떤 이슈인지 모르겠지만 추가가 정상적으로 되고있지 않은 것 같아요. 
로깅을 해봐야할 것 같아 단톡으로 이야기 했던것과 같이 시트 로깅을 해보려고 합니다!
