### ISSUE TITLE
feat: 캐릭터 검색 기능껀

### ISSUE THREAD

**Issue by huise0ng** [git-goods/gitanimals#102]
안녕하세요! 개발자님 
먼저, 귀여운 서비스를 만들어주셔서 감사합니다. 
다름이 아닌 캐릭터 구매를 위해서 레벨 오름차순 내림차순 또는 레벨 설정 등 추가적인 기능으로 원하는 레벨의 동물들을 살 수 있도록 해주세요!

저는 고레벨 캐릭터를 원하고, 오리 같은 경우 매우 많은 캐릭터 존재로 인해 고레벨 동물을 찾기가 매우 어렵습니다!! <br><br>
![스크린샷 2024-07-16 17-17-30](https://github.com/user-attachments/assets/cc647958-2925-41ee-a29c-901fb4a0fc55)

바쁘신 와중에도 제 이슈를 읽어주셔서 감사하고, 다시한번 동물친구들을 개발해주셔서 감사합니다!!🐥

**Comment by sumi-0011** [comment]
안녕하세요 :D  
서비스를 잘 사용해주시고, 의견 남겨주셔서 감사합니다.

전달해주신 의견은 빠르게 반영 후 말씀드리겠습니다 
감사합니다 😄

**Comment by huise0ng** [comment]
바쁘신 와중에도 확인해주셔서 감사합니다 :)

**Comment by devxb** [comment]
안녕하세요~   
해당 기능 추가되었습니다    
@sumi-0011 

<img width="359" alt="스크린샷 2024-09-08 오후 9 11 23" src="https://github.com/user-attachments/assets/2091c72a-c3ff-4aba-826f-62e6b43bd50c">

이용 감사합니다 :)

**Comment by huise0ng** [comment]
반영해주신 점 감사합니다.
