### ISSUE TITLE
shop does not work

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#105]
shop does not work

**Comment by Zerohertz** [comment]
<img width="1628" alt="스크린샷 2024-08-06 오전 11 08 54" src="https://github.com/user-attachments/assets/b44cce4d-00fd-4df3-bd9f-aaa2c1a5bae6">

위 캡쳐와 같이 하얀 바탕으로 렌더링되는 현상을 발견했습니다.

**Comment by hyesungoh** [comment]
말씀해주셔서 감사합니다! 빠르게 수정해볼 수 있도록 해보겠습니다! 👍

**Comment by hyesungoh** [comment]
@Zerohertz 말씀해주신 점 수정해서 배포해 두었습니다! 서비스에 관심 가져주셔서 감사합니다 👍 👍
