### ISSUE TITLE
글자 반전 노린건가요?

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#107]
캐릭터가 왼쪽을 향하면 들고 있던 JAVA, Kotlin 글자도 반전되어 나오는데, 정상적으로 나오면 좋을 것 같습니다.

**Comment by devxb** [comment]
Java Kotlin과 같은 글자는 이미지 형태라서 따로 반전시키는것이 어렵습니다. 
의견 감사합니다
