### ISSUE TITLE
price 최대값이 왜 9223372036854775000??

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#108]
1. 백엔드에서는 price를 long 타입을 사용하고 있어서 9,223,372,036,854,775,807가 최대값이 되어야 합니다.
2. 그런데, javacript 코드에서 price를 number 타입에 담고 있고, 이때 9007199254740991 이상의 값이 들어오게 되면 정확성을 잃습니다.
3. 9223372036854775807 number 타입에 담게 되면 9223372036854776000 이라는 값이 담기게 되어서 400에러가 납니다.
4. bingInt로 처리하면 해결!

**Comment by hyesungoh** [comment]
말씀해주신 점 확인했습니다 ~ 👍 

포인트를 모으는 관점에서만 생각했는데, 판매 시에 해당 이슈를 겪으신 거 같네요 💯
