### ISSUE TITLE
타인의 펫을 사용 가능한 문제

### ISSUE THREAD

**Issue by dutexion** [git-goods/gitanimals#118]
제 깃허브 아이디가 아닌 다른 사용자의 깃허브 아이디를 입력할 경우에도 펫의 사용이 가능합니다

![image](https://github.com/user-attachments/assets/3f9993ae-1029-4278-ad3b-fc670d898916)
![image](https://github.com/user-attachments/assets/a8e76f25-5350-47d0-bd01-e94ebdd7666a)

**Comment by hyesungoh** [comment]
서비스에 관심을 가져주셔서 감사합니다!!

이미지 형태로 제공되다보니까 어쩔 수 없을 거 같아요 🤣 

혹시 생각하신 방법 같은 것이 있으실까용 ??

**Comment by dutexion** [comment]
아하 그렇군요,,
바쁘신 와중에도 답변 주셔서 감사합니다😊

**Comment by devxb** [comment]
넵 맞습니다.
이미지를 른사람도 볼 수 있게해야해서 별도로 인증을 넣기 힘들어요

소중한 의견 감사합니다 👍
