### ISSUE TITLE
커밋 갯수가 반영이 안되는거 같습니다.

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#132]
제 계정(wnsgur1)에 커밋은 1540개 인데 펫에 커밋수는 1401개로 고정되어 있습니다. 뭐가 문젭니까

**Comment by wnsgur1** [comment]
> 제 계정(wnsgur1)에 커밋은 1540개 인데 펫에 커밋수는 1401개로 고정되어 있습니다. 뭐가 문젭니까

<img width="204" alt="스크린샷 2024-09-05 오후 7 57 31" src="https://github.com/user-attachments/assets/a04595ad-64a4-454a-a0f9-49bd13340061">
<img width="783" alt="스크린샷 2024-09-05 오후 7 58 01" src="https://github.com/user-attachments/assets/910e59b8-83b9-4996-9078-de207c323a56">
