### ISSUE TITLE
shop UI/UX 관련 문의입니다

### ISSUE THREAD

**Issue by Dodo9128** [git-goods/gitanimals#137]
안녕하세요?

리뉴얼 후 shop 화면이 제대로 송출되지 않는 것 같아 문의드립니다

1. 최상단 메뉴들이 가려집니다
2. 페이지 진입 시 표시되는 노티들을 끌 수 있었으면 좋겠어요 (웹에서는 무시하면 그만이지만 모바일 웹에서 접속 시에는 계속 최상단을 가리고 노티가 제시하는 액션을 실행하는 것 외에는 끌 수 있는 방법이 없습니다)
3. 모바일 뷰에서 검색 탭을 실행 시 가운데 정렬되지 않아 일부 옵션을 선택할 수 없습니다

![스크린샷 2024-09-13 오후 1 04 13](https://github.com/user-attachments/assets/9b588153-f317-40ad-8127-a81b2eb31a9f)

늘 고생 많으십니다🙇‍♂️

**Comment by devxb** [comment]
안녕하세요! 소중한 의견 감사드립니다 🙇‍♂️ 
노티 같은경우는 마우스로 잡고 위로 드래그 해주시면 없애실 수 있습니다! 추후 더 쉬운 방법으로 고도화 시켜볼게요 ㅎㅎ

추가로 현재 경매장 페이지를 리뉴얼중이라 리뉴얼 후 해결될것 같습니다 
감사합니다
