### ISSUE TITLE
GET https://api.gitanimals.org/users 401 (Unauthorized) 에러

### ISSUE THREAD

**Issue by kugorang** [git-goods/gitanimals#142]
안녕하세요, 올해 추석 연휴 전에 반영된 변경 사항 이후 mypage와 shop에 들어갈 때 아래와 같은 에러가 발생했었습니다.

![image](https://github.com/user-attachments/assets/00d77dec-a086-48df-8a25-19746bfab1c9)

`Application error: a client-side exception has occurred (see the browser console for more information).`

혹시 Token 문제인가 싶어 로그아웃 후에 로그인을 하니 정상 작동되네요.

그래도 Issue는 Issue이니 버그 남겨둡니다. 재밌는 서비스 만들어주셔서 감사합니다!

**Comment by hyesungoh** [comment]
안녕하세요! 이슈 제보해 주셔서 감사합니다 🚀 

해당 버그 인지하였으며 빠르게 수정해 보도록 하겠습니다 !! 말씀 감사합니다 👍 👍 👍

**Comment by hyesungoh** [comment]
말씀해주신 문제 원활히 동작할 수 있도록 변경해 두었습니다 👍 

다시 한 번 감사합니다 ~~

> 현재 토큰 갱신에 대한 로직이 없어, 다시 로그인을 시도하실 수 있도록 한 점 양해 부탁드립니다 🙏
