### ISSUE TITLE
Auction 탭 UI 관련 문의드립니다!

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#147]
> 먼저 너무 귀여운 프로그램 감사드려요! 
> 처음 보자마자 빠진 것처럼 사용하고 있답니다!!

다름이 아니라, 

1. 리뉴얼 된 Auction 탭 **필터** 부분이 **드롭박스 배경 색상 & 글씨 색** 
 둘 다 하얀색으로 동일해서 잘 보이지 않아 피드백 올립니다!
 혹시 의도 된 걸까요!?

![안보임](https://github.com/user-attachments/assets/93786291-8f32-4f47-b84e-53d44999274f)

**Comment by git-good-w** [comment]
@devbini
Thanks for reporting the issue!

**Comment by sumi-0011** [comment]
안녕하세요! 이슈 남겨주셔서 감사합니다 👍

Auction은 최근에 리뉴얼된 부분인데, 예상치 못한 버그가 있었던것 같네요.

빠르게 수정하겠습니다👍 이슈 제보 감사합니다 😊
