### ISSUE TITLE
[BUG] 깃허브 account username을 변경 시

### ISSUE THREAD

**Issue by DevSeongmin** [git-goods/gitanimals#148]

**Comment by hyesungoh** [comment]
안녕하세요! 말씀해주셔서 감사합니다 👍 

좋은 하루되시길 바랄게요!!

**Comment by devxb** [comment]
관심 감사합니다.
해당 이슈 인지했으며
공개되어 있는 커뮤니티에서 제보라서 내용은 삭제하고 close 하겠습니다 🙇‍♂️
