### ISSUE TITLE
동물 뽑기 할 때 카드가 뒤집히지 않고 그대로 종료됩니다.

### ISSUE THREAD

**Issue by kor-sams-dev** [git-goods/gitanimals#152]
![image](https://github.com/user-attachments/assets/f7540a1c-643f-4af1-8598-6020dcab346b)

카드를 선택했지만, 카드가 뒤집혀 동물이 보이지 않고 포인트 차감 및 창이 그대로 종료됩니다!

**Comment by devxb** [comment]
@Todari

이슈해결로 close하겠습니다.
