### ISSUE TITLE
s+ 뽑기 -> a+ 변환

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#153]
s+ 펫 뽑았는데 a+로 뜹니다!!
혹시 오류인지 다른 이유가 있는지 여쭙습니다~

**Comment by git-good-w** [comment]
@0321minji
Thanks for reporting the issue!

**Comment by sumi-0011** [comment]
@devxb 해당 이슈 한번 확인 부탁드립니다!

**Comment by devxb** [comment]
해당 이슈 저도 비슷하게 겪었었는데, 
펫은 정상지급되며, 카드가 돌아가지 않는 이슈는 뽑기 api응답으로 오랜시간이 걸리면 발생하는것으로 추측됩니다. 
@sumi-0011 나중에 날잡고 트래킹한번 해보시죠

**Comment by hyesungoh** [comment]
이거 고쳐진걸로 알아서 닫을게요~
