### ISSUE TITLE
Ex 0%확률

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#154]
0% 확률의 동물들은 가질 수 없는건가요?

**Comment by git-good-w** [comment]
@sooani
Thanks for reporting the issue!

**Comment by hyesungoh** [comment]
안녕하세요! 서비스에 관심을 가져주셔서 감사합니다 🙇 🙇 

0% 확률의 동물은 뽑기에서 나오지 않는 점 공유드립니다! 

이슈는 닫겠습니다! 또 궁금한 점이 있으시면 코멘트 부탁드려요 👍 

> 콜라보 펫의 경우 추후 구매 가능하도록 개발 될 수도 있는 점도 공유드려요 !
