### ISSUE TITLE
fix: 포인트가 음수인 경우

### ISSUE THREAD

**Issue by hyunjung-choi** [git-goods/gitanimals#156]
## Description

오랜만에 접속했더니 제 포인트가 마이너스로 되어있습니다..😢

잘못 표기된 건 아닌가 싶어서 뽑기를 해봤는데 오류가 나고, 상점에서 `buy`를 클릭해도 아무 반응이 없습니다.
펫을 파니까 포인트가 줄어드는 걸 보고 잘못 표기된 건 아니라는 걸 알았습니다.
혹시 포인트 정책이 바뀐건가요..?
할로윈 펫 나왔다고 해서 후다닥 왔는데.. 별안간 빚쟁이가 되어버렸네요...🫠

저번 이슈에도 말씀드렸지만, 해당 프로젝트 너무 귀엽고 재밌게 하고 있어요.. 개발자 분들 화이팅입니다!🥹💞

## ScreenShot

![image](https://github.com/user-attachments/assets/4fb04456-72c3-4986-9c96-470e535f781e)

**Comment by devxb** [comment]
Github total contributions 이 전날보다 줄어든 경우 이미 지급된 Point를 롤백하기 때문에, 포인트가 음수가 될 수 있습니다.
> ex. 커밋 후 커밋내역을 삭제하거나 해당 레포지토리를 private 으로 돌린경우

---
내부적으로 트래킹을 위해 point지급 및 철회 내역을 전부 저장하고 있는데, 
DB 용량문제로 주기적으로 비워주다보니 철회 내역은 남아있지 않네요 ㅠㅠ 

음수 포인트는 의도한 바는 아니며, 현재 정확한 트래킹이 불가능하기 때문에, 포인트는 5000으로 롤백해드렸습니다.

**Comment by devxb** [comment]
항상 관심가져주셔서 감사합니다 🙇‍♂️
