### ISSUE TITLE
리드미에 이미지가 제대로 출력되지 않습니다.

### ISSUE THREAD

**Issue by julyydev** [git-goods/gitanimals#163]
![image](https://github.com/user-attachments/assets/6c9af1ba-9065-40e1-a1dc-ddc3315c63e2)
리드미에서 위 사진처럼 이미지를 제대로 불러오지 못합니다.

![image](https://github.com/user-attachments/assets/8aae05d7-a88d-41bc-8c1a-2255f71bf45d)
이미지 src에 url에 접속해보니 다음과 같은 오류가 발생합니다.

**Comment by hyesungoh** [comment]
제보해주셔서 감사합니다! 빠르게 확인 후 멘션 드릴게요 🙇 

---

@devxb 서버에서 넘겨주는 문자열에 `'`가 안닫힌 곳이 있는 거 같아용

**Comment by devxb** [comment]
안녕하세요,
깃허브 이미지 호출 흐름은 아래와 같은데요
`github -> camo(github 에서 운영하는 url 암호화 및 캐싱 등등 하는 서버) -> render.gitanimals.org`

이때, render.gitanimals.org에서는 정상 응답을 해도 camo에서 이미지를 자르는것 같습니다. 

---

현재 파악된바로는 펫이 많아지면 잘리는것 같아요.
펫을 줄이는 방향으로 재시도 가능하실까요??

**Comment by hyesungoh** [comment]
@julyydev 잠시 깃허브 이미지 캐싱 서버에 문제가 있었던 듯 합니다 🤔 
지금은 정상적으로 동작하여 해당 이슈는 닫을게요!

서비스 애정해 주셔서 감사드립니다 🙇
