### ISSUE TITLE
상점에서 포인트 부족 시에도 배경 및 캐릭터 구매 가능

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#165]
1. 문제 설명
상점에서 포인트로 배경이나 캐릭터를 구매할 때, 포인트가 부족해도 구매가 가능합니다. 이 의도된 동작인지 확인 부탁드립니다. (의도 된 것이라면... 빚 차감을 어떻게 해야는지 ...ㅠㅠ)

2. 추가 제안 사항

배경 미리 보기 기능 : 배경을 구매하기 전에 미리 보거나 예시 이미지를 볼 수 있도록 하면 구매 전 좋은 의사결정을 할 수 있을 거 같습니다.

구매 확인창 추가: 구매 시, 한 번 더 구매 여부를 확인하는 팝업 창이 있으면 실수로 구매하는 것을 방지할 수 있을 것 같습니다.ㅠㅠ 

포인트 관련 FAQ

**Comment by git-good-w** [comment]
@KEJdev
Thanks for reporting the issue!

**Comment by KEJdev** [comment]
앗.. 글이 짤렸는데 마지막 포인트 관련 FAQ는  포인트 사용, 구매 방법 등과 관련한 FAQ가 있으면 보다 쉽게 상점과 포인트 시스템을 이해할 수 있을 것 같아서 적은 의견입니다

**Comment by sumi-0011** [comment]
@KEJdev 
안녕하세요! 의견 남겨주셔서 감사합니다. 
포인트가 부족해도 구매가 가능한 (빚이 생기는?)문제는 빠르게 확인 후 조치해보도록 하겠습니다. 

배경 미리보기 기능과 구매확인창 추가는 있으면 좋을 것 같네요. 
배경 미리보기 기능은 팀 내에서 논의가 필요할것 같아 논의 적용해보도록 하겠습니다. 구매 확인창은 바로 추가해도 좋을 것 같아요 @hyesungoh @devxb 

포인트 FAQ 관련해서는, 현재 저희 서비스를 어떻게 사용할 수 있는지 가이드, 튜토리얼 기능을 준비하고있습니다! 이야기해주신 포인트 사용, 구매 방법을 같이 추가하면 좋을 것 같아요. 의견 감사합니다 👍

저희 서비스를 사용해주시고, 피드백까지 주셔서 감사합니다. 
전달해주신 의견을 받아 좀더 개선된 서비스를 제공할 수 있도록 노력하겠습니다 🙇‍♀️

**Comment by sumi-0011** [comment]
@devxb 포인트가 부족해도 구매 가능한 이슈 서버에서 의도된것인지 확인 부탁드립니다!

**Comment by devxb** [comment]
@KEJdev 
안녕하세요, 버그 제보 감사드립니다. 
해당 이슈 해결되었습니다.

추가로,
`HALLOWEEN_FIELD` -> `CARROT_AND_COIN` 순서로 배경을 구매해주신것으로 보이는데요.
해당 버그를 악용하지 않고, 바로 제보해주셔서 이미 구매하신 배경은 제거하지 않고 포인트는 구매전으로 롤백해드리도록 하겠습니다. 

빠른 제보 감사합니다.
