### ISSUE TITLE
배경을 샀는데 깃허브 readme 파일에 적용이 안됩니다.

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#167]
펫이랑 배경 적용한 부분이 동기화 되는데 시간 이 좀 걸리나요 ?

**Comment by git-good-w** [comment]
@sbi1024
Thanks for reporting the issue!

**Comment by devxb** [comment]
안녕하세요, 깃허브 캐싱 문제로 동기화까지 최대 1시간 소요될 수 있습니다
