### ISSUE TITLE
포인트 관련 건의드립니다.

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#168]
git animals 너무 귀여워서 잘 사용하고 있습니다.
배경 업데이트도 돼서 너무 이쁜 것 같아요! 그런데 경매가 있어도 거래가 잘 이루어지지 않은 것 같아 포인트를 모을 수 있는 방안이 부족한 것 같습니다...
포인트를 수급 기능을 더 늘려주시면 감사하겠습니다~!!

**Comment by git-good-w** [comment]
@cowboysj
Thanks for reporting the issue!

**Comment by sumi-0011** [comment]
안녕하세요 @cowboysj
의견 남겨주셔서 감사합니다! 
포인트은 현재 github commit (잔디)를 통해서만 수급할 수 있는 상황인데,  
팀 내에서 포인트 수급을 할 수 있는 이벤트나, 추가 기능을 넣을 수 있도록 의논해보겠습니다 🙂
