### ISSUE TITLE
돈이 음수입니다..

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#173]
돈이 -74,600원이에요...

**Comment by git-good-w** [comment]
@PresentKim
Thanks for reporting the issue!

**Comment by sumi-0011** [comment]
@devxb 해당 내용 한번 확인 부탁드립니다!

**Comment by PresentKim** [comment]
![Screenshot_20241111_152646_Chrome](https://github.com/user-attachments/assets/4a34c91a-455f-4d8b-83e4-f39a2968710c)

돈이 `-74,600`원이라 마음이 아픕니다.

> PHP 코드를 커밋해서 벌받은 것 같습니다

**Comment by devxb** [comment]
안녕하세요.
제보해주셔서 감사합니다! 

커밋을 하고 레포지토리를 private으로 전환하거나 삭제한 경우 이전 커밋보다 현재 커밋수가 낮아져서 포인트가 음수가 되는 현상이 발생한 것으로 파악되는데요. 해당 이슈 빠르게 수정 하겠습니다. 

포인트는 0원으로 되돌려 드렸습니다!

관심 감사드립니다. 🙇‍♂️

**Comment by PresentKim** [comment]
헉...최근에 오래되서 유지보수 안되는 레포 40개정도 제거했는데 그게 때문이었군요. 해결해주셔서 감사합니다
