### ISSUE TITLE
배경을 변경했는데 적용이 안 됩니다

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#174]
배경을 변경했는데 적용이 안 됩니다 ㅠ

**Comment by git-good-w** [comment]
@dlwhsk0
Thanks for reporting the issue!

**Comment by hyesungoh** [comment]
@dlwhsk0 안녕하세요! 현재는 배경이 적용되신 거 같아요

깃허브 이미지 캐시 기간 이후에 정상적으로 반영이 되는 것으로 생각돼요 🤔 

서비스 애용해주셔서 감사합니다 👍 💌
