### ISSUE TITLE
배경 설정 오류

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#175]
배경을 샀는데 깃허브에 적용이 안돼요.

**Comment by git-good-w** [comment]
@yejinlee99
Thanks for reporting the issue!

**Comment by hyesungoh** [comment]
@yejinlee99 

안녕하세요 서비스를 이용해주셔서 감사드려요 👍 

깃허브 이미지 캐시 문제로 인해 최대 한 시간 이후 정도에 반영되는 점 말씀드립니다 😢 

fyi) #174

**Comment by sumi-0011** [comment]
안녕하세요 @yejinlee99님!
배경 구매 후 마이페이지에서 사용할 배경 선택을 할 수 있습니다. 마이페이지에서 배경 변경까지 진행하셨는데, 깃허브에 적용되지 않은것일까요?
> fyi) Github cache로 인해 배경 설정 후 최대 1시간 내에 배경 변경이 적용될 수 있습니다.
