### ISSUE TITLE
금액에 쉼표 추가

### ISSUE THREAD

**Issue by nahowo** [git-goods/gitanimals#177]
홈페이지에서 My Points에는 금액에 쉼표가 들어가는데, 판매 물품 가격에는 쉼표가 표시되지 않는 것 같아요. 큰 변경은 아니지만 형식이 통일되면 좀 더 보기 편할 것 같아 이슈 올려봅니다!
귀엽고 좋은 서비스 제작 감사합니다 ☺️

**Comment by sumi-0011** [comment]
안녕하세요! 이슈 제보 감사합니다! 
말해주신대로 형식을 통일하면 좋을 것 같은데, 개발을 하다 놓친 부분 같네요 🤔

판매 물품 가격에도 쉼표를 붙일 수 있도록 포맷팅 하는 기능을 추가해두겠습니다. 감사합니다!

**Comment by hyesungoh** [comment]
https://github.com/git-goods/git-animal-client/pull/232 👍 👍
