### ISSUE TITLE
농장 배경을 변경했는데 깃헙 프로필에서는 배경이 반영이 안되고 있습니다.

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#179]
농장 배경을 변경했는데 깃헙 프로필에서는 배경이 반영이 안되고 있습니다.

**Comment by git-good-w** [comment]
@nvrtmd
Thanks for reporting the issue!

**Comment by hyesungoh** [comment]
@nvrtmd

깃허브 이미지 캐시때문에 그렇습니다 😢 

최대 한 시간 이후에 반영이 될 겁니다
> 바로 반영하고 싶으시다면 리드미에 붙어진 이미지 url 뒤에 `#`을 붙이시면 바로 적용된 이미지를 보실 수 있을 거예요

서비스 애용해주셔서 감사합니다 💌
