### ISSUE TITLE
can't apply new purchased green background to my github profile :(

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#183]
i purchased green background for 50,000 gold and tried to apply it by clicking "Copy Link" button and i edited HTML code to README.md file. 
Unfortunately, it didn't work. what's wrong with my settings? i hope it will be fixed soon :)

**Comment by git-good-w** [comment]
@Seung-zedd
Thanks for reporting the issue!

**Comment by devxb** [comment]
안녕하세요, 현재는 정상 반영된것으로 보이며,
깃허브 캐시 문제로 적용까지 최대 1시간 소요될 수 있다는 점 안내드립니다.

**Comment by sumi-0011** [comment]
@Seung-zedd
Hello, it seems to be reflected as normal at the moment,
We would like to inform you that it may take up to an hour to apply due to the GitHub cache problem.

I will add a notice and improve it to fix the cache issue as I see the issue sometimes. Thank you for the issue tip!
