### ISSUE TITLE
S+ 동물 -> A+로 표기

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#184]
10개 뽑기를 통해 S+가 하나 포함된 동물을 뽑았는데 My pet에서 보이지 않아 한번 더 S+이 나올때 까지 뽑아봤습니다.
이후 S+이 포함된 10마리를 뽑앗을때 인벤토리에 추가 실패? 라는 알림이 뜨는것을 확인했어습니다. 인벤토리에 가니 S+이 아닌 A+ 로 표기 되어 들어와있네요 !

**Comment by git-good-w** [comment]
@fbehddn
Thanks for reporting the issue!

**Comment by sumi-0011** [comment]
@fbehddn
안녕하세요 어떤 펫이 S+ -> A+로 표기되었는지 알 수 있을까요?

**Comment by hobiJeong** [comment]
<img width="193" alt="스크린샷 2024-11-21 오후 3 05 56" src="https://github.com/user-attachments/assets/e467936f-5aad-49d1-a05f-85fc49750162">
<img width="270" alt="스크린샷 2024-11-21 오후 3 06 32" src="https://github.com/user-attachments/assets/8e840f7d-af6f-44eb-ab82-7c9bb64693a2">
<img width="162" alt="스크린샷 2024-11-21 오후 3 06 46" src="https://github.com/user-attachments/assets/10a6581a-fe07-45f9-8b0d-b8ace297e268">

뽑기를 했을 때에는 확률이 0.01%라 S+로 표기가 되는데 실제로는 0.12%라서 인벤토리에선 A+로 보이네요

**Comment by devxb** [comment]
안녕하세요, 해당 이슈 수정된어서 close 하겠습니다. cc.sumi-0011

이슈 파악 및 관심 가져주셔서 감사드립니다. 🙇‍♂️
