### ISSUE TITLE
how to merge?

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#189]
i am really enjoying this. how do i merge my pets? I pressed merge but I can't select a second pet. My farm is getting over-crowded, please halp!

**Comment by git-good-w** [comment]
@reiss-koh
Thanks for reporting the issue!

**Comment by sumi-0011** [comment]
@reiss-koh

Hi, can't I merge or can't I choose the second pet?
If you tell me more about the problem situation, I will respond. 

> I think I need a guide. Thank you for the tip.

**Comment by reiss-koh** [comment]
Thank you for the response.

I have identified the problem. As you can see, on my screen (100% zoom on 32 inch monitor), even if i scroll down it does not show the options.
![ss](https://github.com/user-attachments/assets/d002d1a9-e239-420b-98cf-3b405af495dd)

If i zoom out to 80% zoom, I can find it. 

Best

**Comment by sumi-0011** [comment]
@reiss-koh 
Hello. 
Thanks to the issue report, we have discovered a problem that it may not be visible depending on the screen size as well as the ratio. 
We will revise it as soon as possible so that there will be no inconvenience. Thank you for the issue report!
