### ISSUE TITLE
MyPage의 GitHub Custom 펫 변경 시 표시 정보 및 스크롤바 크기 개선 건의드립니다.

### ISSUE THREAD

**Issue by seohyun-lee** [git-goods/gitanimals#190]
안녕하세요! 우연히 Velog에서 소개글을 읽고 서비스를 사용해보게 된 유저입니다.
댓글에서 깃허브 이슈를 통해 개선사항을 받고 계신다고 하여, GitHub Custom의 펫 변경 부분 관련해 개선 의견을 남겨봅니다.

1. 펫 목록에서 정렬 기준을 바로 알기 어려웠습니다. 몇 번의 클릭을 통해 고민한 후 정렬 기준이 레벨 오름차순임을 파악하게 되었는데요. 레벨 내림차순이 더 유용할 것 같다고 생각이 들었습니다.
2. 중복 동물 간 레벨을 비교해 확인하기 어려웠습니다. 가장 레벨이 높은 동물을 나타내고 싶어서, 목록에서 동물별로 레벨을 바로 확인할 수 있으면 좋겠습니다.
3. 스크롤바가 얇아서 마우스로 클릭해 끌기가 어렵다고 느꼈습니다. 좀 더 쉽게 클릭할 수 있도록 두꺼워지면 좋을 것 같습니다.
![image](https://github.com/user-attachments/assets/94c25b47-e14b-42fa-8628-1206d9bdd6f8)

재미있는 프로젝트 만들어주셔서 감사드립니다:)

**Comment by devxb** [comment]
안녕하세요, 소중한 의견 감사드립니다. 
고려해보겠습니다. 🙇‍♂️

**Comment by sumi-0011** [comment]
@seohyun-lee 
안녕하세요! 전달해주신 피드백 확인해보았습니다 :D

- 1번의 경우 펫 레벨이 오름차순으로 되어있었던 것은 인지하지 못했던 부분인데 이야기해주신 것처럼 내림차순이 유용할 것 같네요. 해당 부분은 수정해서 반영해두도록 하겠습니다!
- 1번 이슈를 잘 알지 못했던 것이 레벨이 보여지지 않아서 그런것 같은데, 팀 내에서 상의 후 펫 리스트나, 확장 리스트에서 레벨을 보여줄 수 있으면 좋을 것 같습니다. 
- 확실히 PC 화면인데다가 가로 스크롤이라 스크롤바가 아니면 리스트를 보기 어려울것 같네요 🤔 이부분은 말해주신대로 스크롤바 크기를 키워 쉽게 끌수 있도록 하거나 슬라이더 처럼 마우스 액션으로도 움직이기 쉬운 UI로 개선해보겠습니다. 

신경써서 소중한 피드백 남겨주셔서 감사합니다 😄 
더 나은 서비스를 제공할 수 있도록 노력하겠습니다 👍
