### ISSUE TITLE
레벨 머지 이슈

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#191]
2레벨 이상부터 머지를 하면 절반만 레벨이 오릅니다. 의도된걸까요?!

**Comment by git-good-w** [comment]
@l2yujw
Thanks for reporting the issue!

**Comment by devxb** [comment]
안녕하세요 @l2yujw님 답변이 늦었습니다. 죄송합니다.
2레벨 이상부터는 머지하면 절반씩 오르는것이 의도된 정책이 맞습니다.

관심가져주셔서 감사합니다.
