### ISSUE TITLE
백그라운드 이미지 표시 오류

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#197]
안녕하세요, 샵에서 판매중인 배경 상품 `GRASS_CHRISTMAS_TREE_FIELD` 를 구매 후 적용하였는데, Farm Mode 기준으로 모서리에 녹색 border만 생기고 이미지가 정상적으로 적용되지 않고 있는 것 같습니다.
다른 배경으로 변경해보면 정상적으로 적용되는 것으로 보아, 해당 상품 자체에 관련된 이슈인 것 같은데 확인 부탁드릴 수 있을까요?
감사합니다.

**Comment by git-good-w** [comment]
@reteu5
Thanks for reporting the issue!

**Comment by devxb** [comment]
안녕하세요, 이슈 제보 감사드립니다.
해당 버그는 해결해서 이슈 close 하도록 하겠습니다.

관심 가져주셔서 감사합니다. 🙇‍♂️ 

<img width="603" alt="스크린샷 2024-12-09 오후 11 22 58" src="https://github.com/user-attachments/assets/58c4a574-d10a-4529-ba1d-7686bbbd94fb">
