### ISSUE TITLE
bug: 크리스마스 펫 이동 범위 오류

### ISSUE THREAD

**Issue by ywonchae1** [git-goods/gitanimals#200]
안녕하세요 :>
크리스마스 펫을 뽑았는데, 깃허브에 적용하니 펫의 이동 범위가 하단에 막혀 있는 것 같아요!
수정해 주시면 감사하겠습니다🙇🏻‍♀️🩵
- 너무너무 귀여운 눈사람이 나와서 기뻐요 >v<
<img width="597" alt="Screenshot 2024-12-10 at 21 18 38" src="https://github.com/user-attachments/assets/2763632f-7e99-4497-b116-63dd6726eab0">

**Comment by sumi-0011** [comment]
안녕하세요! 이슈 제보 감사합니다 :D

@devxb 해당 이슈 한번 확인 가능할까요?

**Comment by devxb** [comment]
안녕하세요, 해당 이슈는 펫마다 정확한 이동범위를 계산할 수 없어서 발생하는 버그입니다 ㅠㅠ
정해진 width, height를 벗어나면 사진처럼 잘려서 보입니다.

발전할 수 있는 깃 애니몰즈 되도록 하겠습니다.
감사합니다. 🙇‍♂️
