### ISSUE TITLE
아이템 구매할 때, 확인 alert이 있으면 좋겠어요

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#204]
아이템 구매할 때, 확인 alert이 있으면 좋겠어요. 포인트가 깎이는 거니까...

**Comment by git-good-w** [comment]
@sewonkimm
Thanks for reporting the issue!

**Comment by hyesungoh** [comment]
@sewonkimm 안녕하세요! 저희 서비스 이용해주시고, 좋은 아이디어 말씀해주셔서 감사해요!

내부적으로 의논해볼게요!! cc. @devxb @sumi-0011 

일단 이슈는 닫겠습니다 👍

**Comment by devxb** [comment]
@cjiwxx77 지우님한테도 메일 갈겁니다..!

이슈 닫도록 하겠습니다. 
의견 감사합니다 🙇‍♂️
