### ISSUE TITLE
cant get back pet 

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#206]
why i cant get my pet back in sell list. delete func is terrible :((

**Comment by git-good-w** [comment]
@huydqdev
Thanks for reporting the issue!

**Comment by hyesungoh** [comment]
I did not think about this case! thanks for reporting this issue 👍 

@devxb @sumi-0011 what do you think about 'back in sell list' 
> 펫 판매 리스트를 두고, 다시 살 수 있는 기능 어떰?

**Comment by devxb** [comment]
You can delete your pet from the sell list by following these steps:

1. Click on "Sell List." -> 2.Click the "Edit" button for the pet you want to remove from the sell list. -> 3. Click "Delete."

---

@sumi-0011 @hyesungoh 
이거 펫 경매장에 올리면 sell list에 바로 안 올라오는거 같아 새로고침 한번 해야 보이는듯?
이때 안보여서 이슈 생긴건가
