### ISSUE TITLE
돈이 마이너스가 되었습니다

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#208]
돈이 갑자기 마이너스가 되었습니다. 기존에 몇천 원 남아있던 거로 기억하는데 갑자기 빚이 생겼네요 확인 부탁드립니다

**Comment by git-good-w** [comment]
@Taeheeeeeee
Thanks for reporting the issue!

**Comment by hyesungoh** [comment]
@Taeheeeeeee 레포지토리의 public, private 상태에 따라 음수가 될 수 있어요
@devxb 복구 가능하실까용?

**Comment by devxb** [comment]
안녕하세요. 🙇‍♂️ 
위에서 말씀해주신 것처럼

기존의 `public` 으로 되어있는 레포지토리를 `private` 으로 수정하거나 모종의 이유로 깃허브의 contributions가 줄어든 경우
최종 contributions이 줄어들어 기존에 지급되었던 포인트가 회수됩니다. 이 과정에서 이미 지급된 포인트를 사용하셨다면 포인트가 음수가 될 수 있어요. 

차감된 포인트는 돌려드릴 수 없다는 말씀 전해드립니다.
저희 서비스 사용해 주셔서 감사합니다.
