### ISSUE TITLE
크리스마스 펫 뽑아서 적용했는데

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#209]
붙여넣은 곳의 펫이 바뀌지 않아요

**Comment by git-good-w** [comment]
@dev-jyeon
Thanks for reporting the issue!

**Comment by devxb** [comment]
@dev-jyeon

안녕하세요. 
저희 서비스 사용해주셔서 감사합니다.

펫 적용까지는 캐싱 문제 때문에 최대 1시간이 소요될 수 있습니다.
감사합니다.
