### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#210]
Cannot acquire pet or login through github, even though the authentication was requested and granted, due to the above error.

**Comment by devxb** [comment]
@sumi-0011 
오잉 이름 안 남는경우가 있네?
이건 로그인 안해서 그런거지?

**Comment by sumi-0011** [comment]
> @sumi-0011 오잉 이름 안 남는경우가 있네? 이건 로그인 안해서 그런거지?

응 맞아 로그인 안되어있어서 그런것 같은데, 직접 깃허브 이슈 남겨주시는거 아니면 누군지 알수있는 방법이 없을것 같은데
