### ISSUE TITLE
포인트를 얻을 수 있는 방법

### ISSUE THREAD

**Issue by git-good-w** [git-goods/gitanimals#213]
가지고 있는 펫 팔기 말고 다른 방법은 없나요?! 70,000P 짜리 배경을 사고싶은데 64,705P에서 더 얻을 수 있는 방법이 궁금해요~!!

**Comment by git-good-w** [comment]
@codky
Thanks for reporting the issue!

**Comment by devxb** [comment]
안녕하세요.

포인트는 경매장에서 펫거래 혹은 깃허브 컨트리뷰션(커밋) 등을 통해서 얻을 수 있습니다.

깃애니몰즈를 사랑해주셔서 감사합니다. 🙇‍♂️
