### ISSUE TITLE
fix: point 소모 이후 10 Pet Gotcha 시도할 경우 토스트 메시지 가려짐

### ISSUE THREAD

**Issue by sensecodevalue** [git-goods/gitanimals#222]
### 재현 방법
1. point 모두 소비
2. 10 pet / 10,000p 클릭
3. 카드 클릭
4. 토스트가 카드 선택 모달 뒤에 노출됨

### 개선 제안
1 pat 뽑기랑 플로우가 같아지면 좋을 것 같아요!

### 사진 / 영상

https://github.com/user-attachments/assets/a2179961-6420-42fe-86c5-90d99c4e6122

**Comment by hyesungoh** [comment]
@sumi-0011 가지고 있는 포인트에 따라 그냥 버튼을 disable 처리할까 하는데 어떠세용??

**Comment by sumi-0011** [comment]
> @sumi-0011 가지고 있는 포인트에 따라 그냥 버튼을 disable 처리할까 하는데 어떠세용??

좋아요! 말해주신대로 수정 부탁드릴수 있을까요?
