### ISSUE TITLE
펫을 구매했고 merge도 했는데 반영이 안돼요!

### ISSUE THREAD

**Issue by Hyeri1ee** [git-goods/gitanimals#224]
![image](https://github.com/user-attachments/assets/5e879bc2-2cf5-4d72-8b51-efb845b33747)
![image](https://github.com/user-attachments/assets/2f17bcef-ea6d-46cf-a662-4526f616bc56)
flamingo, 물방울 펫 구매했는데, 반영이 안돼요.
merge또한 했었습니다.

**Comment by devxb** [comment]
@Hyeri1ee 님 안녕하세요.
저희 깃 애니몰즈 사랑해주셔서 감사합니다.

farmType의 경우 깃허브 캐싱 문제로, 변경사항 적용까지 최대 한 시간 소요될 수 있습니다.
현재는 정상적으로 반영된 것 으로 보여서 이슈는 close 하겠습니다.
