### ISSUE TITLE
refactor: 뽑기를 하고 나서 남은 재화가 바로 적용되지 않아요.

### ISSUE THREAD

**Issue by kimgh06** [git-goods/gitanimals#71]
뽑기를 하고 나면 기존 재화에서 빠져나가는 게 반영이 바로 되지 않는 것이 오류인 건가요 아님 의도된 건가요?

추가 의견) 10개 단위로 뽑기 기능도 있으면 좋겠어요!

**Comment by devxb** [comment]
> 10개 단위 뽑기 한다면 API 새로 파주시나여

넵 10개 뽑기 API 추가하겠습니다
관련 정책 (10개 연속뽑기하면 1000원 할인?) 도 고민해볼게요
@sumi-0011

**Comment by hyesungoh** [comment]
해당 작업 완료되어 이슈 닫겠습니다~ 서비스에 관심을 가져주셔서 감사합니다 👍
