### ISSUE TITLE
feat: 기능 및 펫 추가 문의 드립니다

### ISSUE THREAD

**Issue by Dodo9128** [git-goods/gitanimals#74]
1. 나무늘보 캐릭터가 있었으면 좋겠어요
    - 바쁜 태스크가 쌓여 있으실 걸 알기에 .. 추후 가능하다면 .. 부탁드려요
2. 개인 sell history 가 있으면 좋겠습니다
    - 현재는 모든 사용자의 전체 selling history만 제공되고 있는 것 같은데요, 개인 거래 내역도 체크하고 볼 수 있었으면 좋겠어요
3. 개인 페이지의 펫 지정하는 부분이 대표 펫 or 레벨순으로 몇마리만 노출되고, 나머지는 드롭다운 등으로 처리하면 어떨까요?
    - 펫이 많아지다 보니 옆으로 한참 넘겨야 하는 부분이 조금 불편하지 않나 생각합니다
4. 펫 선택란에서 아직 토끼가 제대로 보여지지 않습니다
    - change pet 부분에서만 노출되지 않고, 실제 노출은 잘 되는 것으로 보입니다

**Comment by devxb** [comment]
의견 감사합니다 :)

> 펫 선택란에서 아직 토끼가 제대로 보여지지 않습니다

토끼의 경우 스태틱 서버에 등록이 안되어있는거 같아서 오늘중으로 등록하겠습니다.

> 나무늘보 캐릭터가 있었으면 좋겠어요

나무늘보는 차후에 추가하도록 하겠습니다   
추가 후 @Dodo9128 아이디로 나무늘보를 넣어드릴께요!

**Comment by devxb** [comment]
@Dodo9128 

안녕하세요 :)
금일 나무늘보 펫이 추가되어서, SLOTH_KING을 계정으로 지급해드렸습니다.

<img src="https://raw.githubusercontent.com/git-goods/gitanimals/b2eb1432f9758109c2a8a5acc550780bacbbe739/docs/sloth-king.svg" width="60px" height="100px"/>

**Comment by Dodo9128** [comment]
와 너무 감사합니다!!!
