### ISSUE TITLE
bug: persona select 창 리스팅, 페이지네이션 관련 버그 제보 드립니다

### ISSUE THREAD

**Issue by Dodo9128** [git-goods/gitanimals#85]
안녕하세요?

1. persona select 창에서 어떤 persona도 선택하지 않았을 시, 최하단 persona들의 이름이 짤립니다
(특정 persona를 선택했을 시에는 정렬이 다시 잡히는 것 같습니다)

미선택 시 정렬
![스크린샷 2024-06-20 오후 1 31 09](https://github.com/git-goods/gitanimals/assets/68074001/3b3b8ce8-2c9c-4ebe-9abc-58f50b751a10)
![스크린샷 2024-06-20 오후 1 31 29](https://github.com/git-goods/gitanimals/assets/68074001/08cf03c4-0b70-4ec0-9901-3ccd965850b2)
 
선택 시 정렬
![스크린샷 2024-06-20 오후 1 31 36](https://github.com/git-goods/gitanimals/assets/68074001/db75fa60-7ce6-4374-bf6c-3b4cb6216ca6)
![스크린샷 2024-06-20 오후 1 31 41](https://github.com/git-goods/gitanimals/assets/68074001/ff46912f-5e72-4c1b-bcbd-83e8b90010e6)

2. 기존 화면의 currentPage가 select 시에 그대로 적용되어, select 한 persona의 목록이 currentPage 보다 적을 경우, 아무런 데이터가 노출되지 않습니다.
- 설명이 쉽지 않아 develxb@gmail.com 메일로 화면 녹화 첨부드리겠습니다

**Comment by devxb** [comment]
의견 감사드립니다 :)
페이지가 곧 리뉴얼 될 예정이라 일정 확인 후 수정하도록 하겠습니다.

cc. @hyesungoh @sumi-0011

**Comment by hyesungoh** [comment]
@Dodo9128 안녕하세요! 

말씀해주신 버그 수정해서 현재 배포중에 있습니다 

서비스에 애정을 가져 이슈 제보해주신 점 감사드립니다 👍
