### ISSUE TITLE
bug: 버그 및 펫 추가 문의 드립니다

### ISSUE THREAD

**Issue by ywonchae1** [git-goods/gitanimals#86]
1. 뽑기의 1000points 말풍선에 가려서 펫이 보이지 않습니다.
    <img width="619" alt="Screenshot 2024-06-21 at 15 46 00" src="https://github.com/git-goods/gitanimals/assets/79977182/8e963eed-507b-403a-ab7c-526123f194f8">

2. 거북이 캐릭터가 있으면 좋겠어요
    - 캐릭터 너무 귀여워요.. 너무 좋은 서비스네요 개발해 주셔서 감사합니다!

**Comment by hyesungoh** [comment]
안녕하세요! 개발자 오혜성입니다

말씀해주신 문제 확인했으며, 빠른 시일 내로 수정해 보도록 할게요!

서비스에 애정을 갖고 제보해 주셔서 감사합니다 👍

**Comment by hyesungoh** [comment]
@ywonchae1  버튼 크기 이슈의 경우 작업 완료해서 배포 중에 있습니다 👍 

거북이 캐릭터도 빠른 시일내로 추가해보도록 노력할게요! 감사합니다 👍

**Comment by ywonchae1** [comment]
감사합니다 🐢 ☺️
