### ISSUE TITLE
fix: Point bug

### ISSUE THREAD

**Issue by hyunjung-choi** [git-goods/gitanimals#91]
SHOP에서의 `my points`값과 
![image](https://github.com/git-goods/gitanimals/assets/69616347/3e8dc6a9-a1e7-48f6-9fd7-889d66ee058e)

MY PAGE에서의 `Points`값이 다릅니다.
![image](https://github.com/git-goods/gitanimals/assets/69616347/2e23f19b-a1eb-44d9-ac45-542c18302c72)

원래 다른 속성인 것인가요?
아님 싱크가 맞지 않는 것인가요?

별개로, 해당 서비스 너무 재밌게 이용하고 있습니다. 너무 귀여워요!! 꾸준히 업뎃해주세요..💕

**Comment by devxb** [comment]
@sumi-0011 @hyesungoh 
데이터 소스는 하나라서 마이페이지 쪽 버그일수도 있을거 같습니다.
(Api도 한번 볽용)

**Comment by devxb** [comment]
@hyesungoh @sumi-0011 
요거 아직 안고쳐진거 같아용 🙏
